services:
  web:
    build: .docker/nginx
    container_name: dev-nginx-polymer
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/polymer/:ro
    depends_on:
      - php
      - db

  db:
    image: mariadb:10.6
    container_name: dev-mariadb-polymer
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_DATABASE: 'polymer'
    ports:
      - 3307:3306

  php:
    build: .docker/php
    container_name: dev-php-polymer
    volumes:
      - ./:/var/www/html/polymer:rw
    depends_on:
      - db

volumes:
  mariadb_data:
